namespace FlashOWare.CodeAnalysis.Build.Example.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ExampleGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(PostInitialization);
	}

	private static void PostInitialization(IncrementalGeneratorPostInitializationContext context)
	{
#if ROSLYN3_11
		const string roslyn = "3.11.0";
#elif ROSLYN4_0
		const string roslyn = "4.0.1";
#elif ROSLYN4_4
		const string roslyn = "4.4.0";
#else
		string roslyn = $"Unknown Compiler Version: {typeof(IIncrementalGenerator).Assembly.GetName().Version}";
#endif

		string langVersion = LanguageVersion.Default.MapSpecifiedToEffectiveVersion().ToDisplayString();

		string source = $"""
			// <auto-generated/>
			#nullable enable

			// Current RoslynVersion: {roslyn}
			// Default LangVersion: {langVersion}
			""";
		context.AddSource("AutoGenerated.g.cs", source);
	}
}
