using FlashOWare.CodeAnalysis.Build.Example.Generators;

namespace FlashOWare.CodeAnalysis.Build.Example.Tests.Generators;

[TestClass]
public sealed class ExampleGeneratorTests
{
	[TestMethod]
	public async Task Initialize_Unconditional_PostInitialization()
	{
		await new CSharpSourceGeneratorTest<ExampleGenerator, DefaultVerifier>
		{
			TestState =
			{
				Sources =
				{
					"",
				},
				GeneratedSources =
				{
					(typeof(ExampleGenerator), "AutoGenerated.g.cs", $"""
						// <auto-generated/>
						#nullable enable

						// Current RoslynVersion: Unknown Compiler Version: 4.14.0.0
						// Default LangVersion: {LanguageVersion.CSharp13.ToDisplayString()}
						"""),
				},
			},
		}.RunAsync(CancellationToken.None);
	}
}
