<Project>

  <PropertyGroup Condition="'$(IsRoslynComponent)' == 'true'">
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TestProject)' == 'true' Or '$(IsTestProject)' == 'true'">
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TestProject)' == 'true' Or '$(IsTestProject)' == 'true'">
    <MSTestAnalysisMode>All</MSTestAnalysisMode>
  </PropertyGroup>

</Project>
