# Label opened issues with "triage"
name: Label new issues
run-name: "Label new issue #${{ github.event.issue.number }}"

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  job_label_issue:
    name: Triage new issues
    runs-on: ubuntu-latest
    steps:
      - name: "Triage new issue #${{ github.event.issue.number }}"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
